import protobug
class VideoQualitySetting(protobug.Enum, strict=False):
    VIDEO_QUALITY_SETTING_UNKNOWN = 0
    VIDEO_QUALITY_SETTING_HIGHER_QUALITY = 1
    VIDEO_QUALITY_SETTING_DATA_SAVER = 2
    VIDEO_QUALITY_SETTING_ADVANCED_MENU = 3
